version: '3.3'

services:
  nodeapp:
    container_name: nodeapi
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: bash -c "node app.js"
    restart: always
