version: '3.3'

services:
  nodeapp:
    container_name: nodeapi
    image: nodehai:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: bash -c "node app.js"
    restart: always
